### ISSUE TITLE
What is the purpose of this proposal ?

### ISSUE THREAD

**Issue by c69** [bmeck/proposal-hashbang#2]
If a user is writing a CLI scriptlet in JS, why does he/she need any comments there at all ?

Cases:
- strictly one liner. No reason to have comment.
- multiline "too complex". Needs comment to describe what a particular line is doing.
- multiline "editable". Inline comments allow you to remove some pieces of code from execution.

I would argue, that neither of cases really adds enough value to justify new syntactic character inclusion, especially typeable from standard keyboard (like `#`).

Still maybe people have seen real examples that prove otherwise.

**Comment by ljharb** [comment]
This isn’t about commenting; for a node script to be executable the first line needs a shebang that points to the node binary.
