### ISSUE TITLE
What is being proposed?

### ISSUE THREAD

**Issue by waldemarhorwat** [bmeck/proposal-hashbang#3]
I don't understand this proposal. It seems to let in `#!` almost anywhere. The grammar makes no sense and breaks regular expressions.

**Comment by ljharb** [comment]
I'd expect it to be allowed anywhere `//` is allowed, and treated the same.

**Comment by bmeck** [comment]
`#!` should be allowed at the start of source texts and be treated similarly to a line comment. The intent is not to allow `#!` to be a normal line comment.

**Comment by bmeck** [comment]
The text has been updated to be a new Lexical Goal after talking to @waldemarhorwat
